version: "3.9"
services:
  app:
    build: ./infra/php
    depends_on:
      - db
    env_file:
      - ./src/.env
    volumes:
      - ./src:/data

  db:
    build: ./infra/mysql
    env_file:
      - ./src/.env
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
